# Generated by Django 5.1.1 on 2024-10-06 09:54

import ckeditor.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=80)),
                ('message', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('tour_type', models.CharField(choices=[('Trekking', 'Trekking'), ('Safari', 'Safari'), ('Island', 'Island'), ('More', 'More')], max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('tour_descr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('popular', models.BooleanField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('publish', models.DateTimeField(default=datetime.datetime.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('tour_name', models.CharField(max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.tour')),
            ],
        ),
    ]
