# Generated by Django 5.1.1 on 2024-10-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='popular',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('beach', 'Beach')], max_length=20),
        ),
    ]
