# Generated by Django 3.1.1 on 2024-10-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20241011_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
