# Generated by Django 3.1.1 on 2024-10-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_tour_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
