# Generated by Django 3.1.1 on 2024-10-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_tour_tour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(upload_to='static/images/tours_img'),
        ),
    ]
