# Generated by Django 3.1.1 on 2024-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20241021_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/images/tours_img'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/images/tours_img'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/images/tours_img'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image4',
            field=models.ImageField(null=True, upload_to='static/images/tours_img'),
        ),
    ]
