# Generated by Django 3.1.1 on 2024-10-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20241021_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tourdays',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
