# Generated by Django 3.1.1 on 2024-10-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_tour_tourdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='agent_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
