# Generated by Django 3.1.1 on 2024-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tourdays',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
