# Generated by Django 3.1.1 on 2024-11-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='video_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
