# Generated by Django 4.2.16 on 2024-11-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mobile_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
