# Generated by Django 4.2.16 on 2024-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_profile_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
